spring.application.name=DovaProjekt-Backend

# Supabase JWT Configuration
supabase.jwt.secret=ItMoA7m+8Mk1VFQJ2QMqtYOEj/xaSkFV0K4OOWPGRgJspbWw4bwc5YCr7uQ+hx8fgZoO7LoITfYBHsMMWBKCqQ

# Supabase PostgreSQL Database Configuration (Transaction Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.kbayrajvfdmvjuxtnhbw
spring.datasource.password=vtk0PhKKW2zU0ruv

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
