# Supabase JWT Configuration
supabase.jwt.secret=ItMoA7m+8Mk1VFQJ2QMqtYOEj/xaSkFV0K4OOWPGRgJspbWw4bwc5YCr7uQ+hx8fgZoO7LoITfYBHsMMWBKCqQ==


# Supabase PostgreSQL Database Configuration (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.kbayrajvfdmvjuxtnhbw
spring.datasource.password=vtk0PhKKW2zU0ruv

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

supabase.url=https://kbayrajvfdmvjuxtnhbw.supabase.co
supabase.service_role_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYXlyYWp2ZmRtdmp1eHRuaGJ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDY2MjM5MiwiZXhwIjoyMDgwMjM4MzkyfQ.thm-lIQi0NsUC8C4W7N5asTWmm8WrdUC6Hs3wURC2c4
